### PR TITLE
Jdoc updates

### PR DESCRIPTION
**Pull request by GijsWeterings**

### CODE REVIEW

**Comment by JeremybellEU** [comment]
Javadoc changes look good. I think a more reasonable pom version at the current stage is 0.1-BETA, as the current version is not ready for production just yet.

**Comment by JWGmeligMeyling** [comment]
maybe reset the pom.xml. Javadoc changes are ok!

**Comment by Azkle** [comment]
I indeed would remove the "-snapshot" from the pom. 
We might want to replace it with something,because it's not a version that should be in production.

The others look good.

**Comment by Azkle** [comment]
LGTM, good to merge.

**Comment by JWGmeligMeyling** [comment]
Good to merge, Travis false alarm.

**Pull request merged**
