### PR TITLE
Written 3 more EndToEndTests.

### PR DESCRIPTION
**Pull request by JeremybellEU**
Took quite some effort to get them working, as I had to come up with solutions for POST-requests and to mock the SoundCloud oAuth login.

Not the nicest code, but it works ;p

### CODE REVIEW

**Comment by JeremybellEU** [comment]
Test is failing, because of an invalid version of Hatbox (we suspect).
However the local version of @JWGmeligMeyling is working, so we might want to look into that.

Else we just remove that last test-case.

**Comment by Azkle** [comment]
The test are looking good.

**Comment by JWGmeligMeyling** [comment]
It wasnt duplication, because the TestPackageRunner doesnt use the TestDbModule... And shouldnt. Because the persist service is already started by the webserver.

**Comment by JeremybellEU** [comment]
The EndToEndTests used the same initialization as the TestPackageRunner.main (as I copy-pasted it). Therefore I deduplicated that code, which I should have done from the beginning ;p

Sadly the issue still exists, whereas it runs succesfully on my machine.

**Comment by JeremybellEU** [comment]
Good fix, merging!

**Pull request merged**
