### PR TITLE
Truncating of messages. Fixes #84.

### LINKED ISSUE #84: Implement the  r-tree
Implement the r-tree to be scalable. Pair with @JWGmeligMeyling

### PR DESCRIPTION
**Pull request by JeremybellEU**
Fixes https://github.com/MoodCat/MoodCat.me-Frontend/issues/84

### CODE REVIEW

**Comment by Azkle** [comment]
It works so, LGTM

**Comment by JWGmeligMeyling** [comment]
I'm going to think about this one for a sec.

**Comment by JWGmeligMeyling** [comment]
I wouldnot truncate. We should consider this a bad request and throw an exception. And prevent in the frontend that such messages can be typed by setting a limit on the input field.

**Comment by JeremybellEU** [comment]
Changed to exception and a fail-fast approach.

**Comment by JWGmeligMeyling** [comment]
We need this, will merge! :+1:

**Pull request merged**
