### PR TITLE
Reporting added to pom.xml

### PR DESCRIPTION
**Pull request by JeremybellEU**

### CODE REVIEW

**Comment by JWGmeligMeyling** [comment]
:+1:

**Comment by Azkle** [comment]
:+1:

**Comment by JWGmeligMeyling** [comment]
Please fix the checkstye issues first.

**Comment by JeremybellEU** [comment]
This branch now also contains the content of #66 . We might want to close that branch and continue with this one.

**Comment by JWGmeligMeyling** [comment]
These are 7 commits for +/- 100 line changes. Which I think is absurd. I think it's best to rebase on the master and squash the commits together: `git rebase -i master` and then change `pick` to `s` for all commits except the first one to bring them together.

**Comment by JWGmeligMeyling** [comment]
Rebased in #67

**Comment by Jaapp-** [comment]
All seems fine, merging.

**Pull request merged**
